# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\traservice\" \n\x0cHelloRequest\x12\x10\n\x08teamName\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"i\n\x0e\x43ommandMessage\x12\x10\n\x08teamName\x18\x01 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x05\x12\x0e\n\x06unitId\x18\x03 \x01(\r\x12\x11\n\toperation\x18\x04 \x01(\t\x12\x11\n\textraJson\x18\x05 \x01(\t2\x9f\x01\n\rFireRaService\x12:\n\x08SayHello\x12\x17.raservice.HelloRequest\x1a\x15.raservice.HelloReply\x12R\n\x16\x43ommunicateWithStreams\x12\x19.raservice.CommandMessage\x1a\x19.raservice.CommandMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=28
  _globals['_HELLOREQUEST']._serialized_end=60
  _globals['_HELLOREPLY']._serialized_start=62
  _globals['_HELLOREPLY']._serialized_end=91
  _globals['_COMMANDMESSAGE']._serialized_start=93
  _globals['_COMMANDMESSAGE']._serialized_end=198
  _globals['_FIRERASERVICE']._serialized_start=201
  _globals['_FIRERASERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
